### ISSUE TITLE
Rewind tab history is mistaken for duplicates !

### ISSUE THREAD

**Issue by ghost** [psychowood/dont-dupe-tabs#1]

**Comment by psychowood** [comment]
What is the "Rewind tab history"?

**Comment by ghost** [comment]
Top left arrow

**Comment by psychowood** [comment]
Which platform? I don't see that behaviour on macOS, moreover the "back" action shouldn't activate the extension since it is not a new tab but rather a navigation action (i.e. even if the back action navigates to an already open url, the tab isn't closed).

**Comment by ghost** [comment]
![bug](https://user-images.githubusercontent.com/28247198/32405804-14405d60-c1a7-11e7-87dd-fbd469b3c0d2.gif)

Windows 7

**Comment by psychowood** [comment]
Thanks. So you are trying to open a new tab with the back arrow (ctrl+click)?

**Comment by ghost** [comment]
yes

**Comment by psychowood** [comment]
I suppose Chrome opens the new tab with the current url instead of the "back" one. I'll let you know.

**Comment by ghost** [comment]
Similar extensions work fine

**Comment by ghost** [comment]
![bug](https://user-images.githubusercontent.com/28247198/32406533-4159b1bc-c1b5-11e7-862d-a71056820348.gif)

**Comment by psychowood** [comment]
Fixed in adbe89eb519cdf7e9145a63385201efc6aae4901. Pushing to the web store.

EDIT: Store updated with v0.2

**Comment by ghost** [comment]
Thank you
